# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_name',
            new_name='phone_number',
        ),
    ]
